name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build and test
      run: npx --package mini-cross@0.15.2 mc --no-tty _ make
